### ISSUE TITLE
Stabilize message gives incorrect number of stabilize points

### ISSUE THREAD

**Issue by jsills3110** [spencermcghin/mush_test#201]
I have stabilize 3, but the message says 1
![image](https://user-images.githubusercontent.com/15237533/92314086-154a4100-ef88-11ea-9ed6-8effdff6fe11.png)

**Comment by jsills3110** [comment]
This was another message that correctly told me the number of stabilize, but it's a different message
![image](https://user-images.githubusercontent.com/15237533/92314142-b638fc00-ef88-11ea-86c2-a926e047b943.png)

**Comment by spencermcghin** [comment]
Fixed
