### ISSUE TITLE
Need to add all the CharGen new Attribute skills

### ISSUE THREAD

**Issue by nhillen** [spencermcghin/mush_test#230]
Need to add all the CharGen new Attribute skills for the following:

> Gunner
> Archer
> Shields
> Melee Weapons
> Armor Proficiency
> Sniper

**Comment by spencermcghin** [comment]
Gunner done

**Comment by spencermcghin** [comment]
Sniper done

**Comment by spencermcghin** [comment]
These are done. Thanks @nhillen.
